# evaluation/configuration/config.yaml

# Paths
dataset_dir: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/data/test_data_set_full/structured3d_perspective_full'
desdf_path: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/data/test_data_set_full/desdf'
log_dir_depth: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/modules/Final_wights/depth/final_depth_model_checkpoint.ckpt'
log_dir_semantic: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/modules/Final_wights/semantic/final_semantic_model_checkpoint.ckpt'


split_file: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/data/test_data_set_full/structured3d_perspective_full/split.yaml'
prob_vol_path: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/data/test_data_set_full/prob_vols_mask2former'
#------------------------------------------
results_dir: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/results/Clean_Time_Exp'

#------------------------------------------
combined_prob_vols_net_path: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/logs/combined/expected_pose_pred/combined_prob_vols_net_type-expected_pose_pred_net_size-6k_dataset_size-medium_epochs-99/combined_net-epoch=58-loss-valid=7.16.ckpt'
combined_net_size: "6k"

#------------------------------------------
# Dataset parameters
L: 0

# Depth network parameters
D: 128
d_min: 0.1
d_max: 15.0
d_hyp: -0.2

#Localize:
F_W: 0.59587643422
V: 7
# depth_checkpoint: 'depth/depth_net-epoch=94-loss-valid=0.47.ckpt'
# depth_checkpoint: 'depth/final_depth_model_checkpoint.ckpt'

# Semantic network parameters
num_classes: 4

# Evaluation parameters
prediction_type: 'combined'  # Options: 'depth', 'semantic', 'combined', 'all'
use_ground_truth_depth: false  # Set to true to use ground truth depth
use_ground_truth_semantic: false  # Set to true to use ground truth semantics
use_saved_prob_vol: false
num_of_scenes: 50
max_h: 1760
max_w: 1760

# Weight combinations for combined evaluation
weight_combinations:
  # - [1.0, 0]  # Only depth
  # - [0.9, 0.1]
  # - [0.8, 0.2]
  - [0.7, 0.3]
  # - [0.6, 0.4]
  # - [0.5, 0.5]
  # - [0.4, 0.6]
  # # - [0.3, 0.7]
  # # - [0.2, 0.8]
  # # - [0.1, 0.9]
  # - [0, 1.0]  # Only Semantic

top_k: 3

log_dir_semantic_maskformer: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/logs/mask2Former_semantics_with_small_50k_no_augmentaion/semantic/semantic_net-epoch=15-loss-valid=0.32.ckpt'
use_maskformer: true

log_dir_semantic_maskformer_small: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/modules/Final_wights/semantic/mask2former_tiny_50k_semantic_net-epoch=19-loss-valid=0.34.ckpt'
use_small_maskformer: true

use_room_aware: true
room_aware_checkpoint: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/logs/room_type_Resnet50_pre_trained/semantic/semantic_net-epoch=03-loss-valid=1.00.ckpt'
room_selection_threshold: 0.8
num_room_types: 16

log_dir_semantic_and_room_aware: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/logs/resnet_semantic_and_room_type_with_cls/semantic/semantic_net-epoch=14-loss-valid=1.31.ckpt'
semantic_net_type: "resnet_cls"
room_data_dir: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/data/test_data_set_full/structured3d_perspective_full_with_room_types'