# evaluation/configuration/config.yaml

# Paths
dataset_dir: 'Data\S3D'
depth_weights: 'modules\weights\s3d\final_depth.ckpt'
semantic_weights: 'modules\weights\s3d\final_semantic.ckpt'

#------------------------------------------
results_dir: 'results\s3d_perspective\test_set\'

#Localize:
F_W: 0.59587643422
V: 9

# Semantic network parameters
num_classes: 4

# Evaluation parameters
use_ground_truth_depth: false  # Set to true to use ground truth depth
use_ground_truth_semantic: false  # Set to true to use ground truth semantics
num_of_scenes: 1

# Weight combinations for combined evaluation
weight_combinations:
  # - [1.0, 0]  # Only depth
  # - [0.9, 0.1]
  # - [0.8, 0.2]
  # - [0.7, 0.3]
  - [0.6, 0.4]
  # - [0.5, 0.5]
  # - [0.4, 0.6]
  # - [0.3, 0.7]
  # - [0.2, 0.8]
  # - [0.1, 0.9]
  # - [0, 1.0]  # Only Semantic

# refine parameters
top_k: 5
min_dist_m: 0.1              # Minimum distance in meters
alpha_similarity: 0.3        # Alpha similarity threshold
resolution_m_per_pixel: 0.1  # Resolution in meters per pixel

use_room_aware: true
room_selection_threshold: 0.8
num_room_types: 16

is_zind: False