# config_experiments.yaml

# ===========================================================================
# Base dataset and model paths
# (These come from your original config.yaml)
# ===========================================================================
dataset_dir: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/data/test_data_set_full/structured3d_perspective_full'
desdf_path: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/data/test_data_set_full/desdf'

split_file: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/data/test_data_set_full/structured3d_perspective_full/split.yaml'
prob_vol_path: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/data/test_data_set_full/prob_vols_mask2former'

# Path to store experiment results
results_dir: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/results/s3d/refin_experiments/parameter_experiments_250_val/'

# (If you have a combined-prob-vol net path)
combined_prob_vols_net_path: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/logs/combined/expected_pose_pred/combined_prob_vols_net_type-expected_pose_pred_net_size-6k_dataset_size-medium_epochs-99/combined_net-epoch=58-loss-valid=7.16.ckpt'
combined_net_size: "6k"

# ===========================================================================
# Model checkpoints
# ===========================================================================
log_dir_depth: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/modules/Final_wights/depth/final_depth_model_checkpoint.ckpt'
log_dir_semantic: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/modules/Final_wights/semantic/final_semantic_model_checkpoint.ckpt'
log_dir_semantic_maskformer: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/logs/mask2Former_semantics_with_small_50k_no_augmentaion/semantic/semantic_net-epoch=15-loss-valid=0.32.ckpt'
log_dir_semantic_maskformer_small: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/modules/Final_wights/semantic/mask2former_tiny_50k_semantic_net-epoch=19-loss-valid=0.34.ckpt'
room_aware_checkpoint: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/logs/room_type_Resnet50_pre_trained/semantic/semantic_net-epoch=03-loss-valid=1.00.ckpt'
log_dir_semantic_and_room_aware: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/logs/resnet_semantic_and_room_type_with_cls/semantic/semantic_net-epoch=14-loss-valid=1.31.ckpt'

# ===========================================================================
# Dataset parameters
# ===========================================================================
L: 0

# Depth network parameters
D: 128
d_min: 0.1
d_max: 15.0
d_hyp: -0.2

# Raycasting / Localize parameters
F_W: 0.59587643422
V: 7

# Semantic network parameters
num_classes: 4
num_room_types: 16
semantic_net_type: "resnet_cls"

# Combined weighting (we'll still let the parameter-sweep code override if needed)
weight_combinations:
  - [0.5, 0.5]

# Flags for how to handle depth/semantics
prediction_type: 'combined'
use_ground_truth_depth: false
use_ground_truth_semantic: false
use_saved_prob_vol: false
use_room_aware: true
room_selection_threshold: 0.8
use_maskformer: true
use_small_maskformer: true

# For the entire dataset
num_of_scenes: -1
max_h: 1760
max_w: 1760

# Room polygons
room_data_dir: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/data/test_data_set_full/structured3d_perspective_full_with_room_types'

# Just provide a single default top_k, alpha_similarity, min_dist_m here;
# the run_experiments script will override them in its parameter loops
top_k: 2
alpha_similarity: 0.1
min_dist_m: 1.0
resolution_m_per_pixel: 0.1
