# evaluation/configuration/config_eval_diffusion.yaml

# Paths
dataset_dir: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/data/test_data_set_full/structured3d_perspective_full'
prob_vol_path: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/data/test_data_set_full/prob_vols'
split_file: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/data/test_data_set_full/structured3d_perspective_full/split.yaml'

# Results directory
results_dir: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/results/full/weight_prediction_net/new_prob_vols/with_attention'

diffusion_model_checkpoint: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/logs/weight_predictor_nets/new_prob_vols/with_attention/weight_predictor_net_epochs-50_net_size-large_acc_only-True-loss_type-mse-v4/weight_predictor_net-epoch=27-loss-valid=3.45027.ckpt'

add_plots: False
batch_size: 1
NET_SIZE: 'large'  # Options: 'small', 'medium', 'large', 'x-large'
# Options: 'tiny', 'small', 'medium', 'full'
DATA_SET_SIZE: 'medium'

L: 0
acc_only: True

pad_to_max: True
max_h: 1760
max_w: 1760


# Localization parameters
F_W: 0.59587643422
V: 7

 