# evaluation/configuration/config.yaml

# Paths
dataset_dir: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/data/test_data_set_full/structured3d_perspective_full'
desdf_path: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/data/test_data_set_full/desdf'

log_dir_depth: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/modules/Final_wights/depth/final_depth_model_checkpoint.ckpt'
log_dir_semantic: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/modules/Final_wights/semantic/final_semantic_model_checkpoint.ckpt'

combined_prob_vols_small_net: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/logs/combined/Final_test/combined_prob_vols_net_type-large_dataset_size-medium_epochs-30_loss-nll_acc_only-True/final_combined_model_checkpoint.ckpt'

split_file: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/data/test_data_set_full/structured3d_perspective_full/split.yaml'

results_dir: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/results/prob_vols/acc_only/combined_prob_vols_net_type-large_dataset_size-medium_epochs-30_loss-nll_acc_only-True'


# Dataset parameters
L: 0

# Depth network parameters
D: 128
d_min: 0.1
d_max: 15.0
d_hyp: -0.2

#Localize:
F_W: 0.59587643422
V: 7
# depth_checkpoint: 'depth/depth_net-epoch=94-loss-valid=0.47.ckpt'
# depth_checkpoint: 'depth/final_depth_model_checkpoint.ckpt'

# Semantic network parameters
num_classes: 4

# Evaluation parameters
prediction_type: 'combined'  # Options: 'depth', 'semantic', 'combined', 'all'
use_ground_truth_depth: false  # Set to true to use ground truth depth
use_ground_truth_semantic: false  # Set to true to use ground truth semantics

# Weight combinations for combined evaluation
weight_combinations:
  - [1.0, 0.0]  # Depth-only
  - [0.0, 1.0]  # Semantic-only
  - [0.5, 0.5]
  - [0.6, 0.4]
  - [0.7, 0.3]
  - [0.8, 0.2]
  - [0.9, 0.1]
