# evaluation/configuration/config.yaml

# Paths
dataset_dir: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/data/test_data_set_full/structured3d_perspective_full'
desdf_path: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/data/test_data_set_full/desdf'
split_file: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/data/test_data_set_full/structured3d_perspective_full/split.yaml'
prob_vol_path: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/data/test_data_set_full/prob_vols'
best_map_path: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/data/test_data_set_full/combine_map_vector'
#------------------------------------------
map_predictor_pl_log_dir: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/logs/best_map_prediction/new_vector_default_0_5_with_0.9/map_predictor_net_epochs-100_net_size-large_train_dataset_size-full-v2/map_predictor_net-epoch=27-loss_valid=2.78837.ckpt'
results_dir: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/results/full/best_map_eval/new_vector_large'
#------------------------------------------
# Dataset parameters
L: 0

# Depth network parameters
D: 128
d_min: 0.1
d_max: 15.0
d_hyp: -0.2

#Localize:
F_W: 0.59587643422
V: 7

# Semantic network parameters
num_classes: 4

num_of_scenes: -1
pad_to_max: True
max_h: 1760
max_w: 1760

# Weight combinations for combined evaluation
weight_combinations:
  - [1.0, 0.0]  
  - [0.9, 0.1]  
  - [0.5, 0.5]
  - ["use_best_map_net", ""]

best_map_weight_combinations:
  - [1.0, 0.0] 
  - [0.9, 0.1] 
  - [0.5, 0.5]
net_size: 'large'  # Options: 'small', 'medium', 'large', 'x-large'
log_dir: 'logs'
lr: 0.0001