# evaluation/configuration/config.yaml

# Paths
dataset_dir: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/data/zind/zind_data_set'
desdf_path: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/data/zind/desdf'
log_dir_depth: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/logs/zind/08_10/depth/final_depth_model_checkpoint.ckpt'
log_dir_semantic: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/logs/zind/08_10/semantic/semantic_net-epoch=11-loss-valid=0.34.ckpt'
results_dir: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/results/full/visualizations/Zind'


# Dataset parameters
L: 0

# Depth network parameters
D: 128
d_min: 0.1
d_max: 15.0
d_hyp: -0.2

# Semantic network parameters
num_classes: 4

# Evaluation parameters
prediction_type: 'combined'  # Options: 'depth', 'semantic', 'combined', 'all'

# Weight combinations for combined evaluation
weight_combinations:
  - [1.0, 0.0]  # Depth-only
  - [0.0, 1.0]  # Semantic-only
  - [0.5, 0.5]
  # - [0.6, 0.4]
  # - [0.7, 0.3]
  # - [0.8, 0.2]
  # - [0.9, 0.1]


scene_numbers:
  # - 0
  # - 3250
  # - 3251
  # - 3252
  # - 3253
  # - 3254
  # - 3255
  # - 3256
  # - 3257
  # - 3258
  # - 3259
  # - 3260
  # - 3261
  - 3262
  - 3263
  - 3264
  - 3265
  - 3266
  - 3267
  - 3268
  - 3269
  - 3270
