# config.yaml
dataset: "fixed_fp_data_set"
dataset_path: "/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/data/zind"
ckpt_path: "./logs/zind/fixed_fp/zind_depth_all_scenes/"
epochs: 100
batch_size: 8
lr: 0.001
shape_loss_weight: 20
model_type: "depth"
# Depth net parameters
depth_net:
  L: 0
  D: 128
  d_min: 0.1
  d_max: 15.0
  d_hyp: -0.2
  F_W: 3 / 5

# Augmentation settings
augmentation:
  add_rp: True
  roll: 0
  pitch: 0

fov: 80

image_augment: false
image_augment_noise_std: 0.02

room_data_dir: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/data/zind/fixed_fp_data_set'

dataset_pano : ""
is_training: True