# config_evaluate_top_k.yaml

dataset: "structured3d_perspective_full"
dataset_path: "/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/data/test_data_set_full"
top_k_results_dir: "/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/modules/top_k/results_dist_1_top_10"
split_file: "/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/data/test_data_set_full/structured3d_perspective_full/split.yaml"
checkpoint: "/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/modules/top_k/logs/best_k_net_bs-16_ep-100_fp-True_time-20250123-1222-train_100_epochs/final_best_k_net_checkpoint.ckpt"  
ckpt_path: "/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/modules/top_k/evaluate_results"  
use_fp: True
poses_filename: "poses.txt"
epochs: 100  # You can keep this as is or adjust if needed
batch_size: 16
lr: 0.001
num_workers: 8
